version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap && kong start"
    networks:
      - kong-net

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net

  spring-boot-app1:
    image: spring-boot-app:latest
    container_name: spring-boot-app1
    build:
      context: ./spring-boot-app
    ports:
      - "8081:8080"
    networks:
      - kong-net

  spring-boot-app2:
    image: spring-boot-app:latest
    container_name: spring-boot-app2
    build:
      context: ./spring-boot-app
    ports:
      - "8082:8080"
    networks:
      - kong-net

  konga:
    image: pantsel/konga
    environment:
      - NODE_ENV=production
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=konga_db
    ports:
      - 1337:1337
    depends_on:
      - kong-database
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
